### ISSUE TITLE
Possible incorrect version for testing part

### ISSUE THREAD

**Issue by bonfilsd** [cloudfoundry/binary-builder#23]
Hi, i come to you for notify a possible incorrect version for testing part in the code.
Indeed, in https://github.com/cloudfoundry/binary-builder/blob/master/spec/integration/httpd_spec.rb#L8-L9
it's specified http 2.4.17.
I think the correct code for http 2.4.23 (current version) is :

```ruby
run_binary_builder('httpd', '2.4.23', '--md5=04f19c60e810c028f5240a062668a688')
@binary_tarball_location = Dir.glob(File.join(Dir.pwd, 'httpd-2.4.23-linux-x64*.tgz')).first
```

Have a good day

**Comment by sesmith177** [comment]
Thanks for the note! We generally don't put too much effort into keeping the versions on the binary-builder specs up-to-date with the latest release version numbers. This is because we do not expect (and have not generally experienced) the build steps to change between patch releases of the things we build
